/**
 * Icon Schema Generator
 * 
 * This script scans the assets folder for icon SVG files and generates
 * a Shopify schema-compatible JSON array for use in section dropdowns.
 * 
 * HOW IT WORKS:
 * 1. Scans assets/ folder for files matching pattern: icon-{name}.svg
 * 2. Extracts icon names from filenames (e.g., "icon-truck.svg" → "truck")
 * 3. Generates a formatted label (e.g., "truck" → "Truck")
 * 4. Outputs JSON that can be copy-pasted into any section's schema
 * 
 * USAGE:
 *   bun run scripts/generate-icon-schema.ts
 * 
 * OUTPUT:
 *   - Prints JSON to console (copy-paste ready)
 *   - Saves to snippets/icon-schema-options.liquid (for reference)
 */

import { readdir, writeFile } from "fs/promises";
import { join } from "path";

const ASSETS_DIR = join(import.meta.dir, "..", "assets");
const OUTPUT_FILE = join(import.meta.dir, "..", "snippets", "icon-schema-options.liquid");

interface IconOption {
  value: string;
  label: string;
}

/**
 * Converts a kebab-case icon name to a Title Case label
 * e.g., "credit-card" → "Credit Card"
 */
function toTitleCase(str: string): string {
  return str
    .split("-")
    .map(word => word.charAt(0).toUpperCase() + word.slice(1))
    .join(" ");
}

/**
 * Scans the assets directory for icon files
 */
async function getIconFiles(): Promise<string[]> {
  try {
    const files = await readdir(ASSETS_DIR);
    return files
      .filter(file => file.startsWith("icon-") && file.endsWith(".svg"))
      .sort();
  } catch (error) {
    console.error("Error reading assets directory:", error);
    return [];
  }
}

/**
 * Extracts icon name from filename
 * e.g., "icon-truck.svg" → "truck"
 */
function extractIconName(filename: string): string {
  return filename.replace("icon-", "").replace(".svg", "");
}

/**
 * Generates schema options array
 */
function generateSchemaOptions(iconFiles: string[]): IconOption[] {
  const options: IconOption[] = [
    { value: "none", label: "None" }
  ];

  for (const file of iconFiles) {
    const name = extractIconName(file);
    options.push({
      value: name,
      label: toTitleCase(name)
    });
  }

  return options;
}

/**
 * Generates the full schema setting object
 */
function generateFullSchemaSetting(options: IconOption[]): object {
  return {
    type: "select",
    id: "icon",
    label: "Icon",
    options: options,
    default: "none"
  };
}

/**
 * Main execution
 */
async function main() {
  console.log("🔍 Scanning for icons in assets folder...\n");
  
  const iconFiles = await getIconFiles();
  
  if (iconFiles.length === 0) {
    console.log("❌ No icon files found (pattern: icon-*.svg)");
    return;
  }

  console.log(`✅ Found ${iconFiles.length} icon files:\n`);
  iconFiles.forEach(file => console.log(`   - ${file}`));
  
  const options = generateSchemaOptions(iconFiles);
  const fullSetting = generateFullSchemaSetting(options);

  // Output the options array (for copy-pasting into existing settings)
  console.log("\n" + "=".repeat(60));
  console.log("📋 COPY-PASTE: Options array for schema\n");
  console.log('"options": ' + JSON.stringify(options, null, 2));
  
  // Output the full setting (for creating new icon selectors)
  console.log("\n" + "=".repeat(60));
  console.log("📋 COPY-PASTE: Full setting object\n");
  console.log(JSON.stringify(fullSetting, null, 2));

  // Save to a liquid file for reference
  const liquidContent = `{% comment %}
  AUTO-GENERATED ICON SCHEMA OPTIONS
  Generated by: bun run scripts/generate-icon-schema.ts
  Last updated: ${new Date().toISOString()}
  
  Copy the JSON below into your section schemas.
  Available icons: ${iconFiles.length}
{% endcomment %}

{% comment %} Options Array (paste into existing select settings) {% endcomment %}
<!--
"options": ${JSON.stringify(options, null, 2)}
-->

{% comment %} Full Setting Object (paste to create new icon selector) {% endcomment %}
<!--
${JSON.stringify(fullSetting, null, 2)}
-->

{% comment %} Available Icon Names {% endcomment %}
<!--
${iconFiles.map(f => extractIconName(f)).join(", ")}
-->`;

  await writeFile(OUTPUT_FILE, liquidContent);
  console.log("\n" + "=".repeat(60));
  console.log(`💾 Saved reference file: snippets/icon-schema-options.liquid`);
  console.log("\n✨ Done! Copy the JSON above into your section schemas.");
}

main().catch(console.error);
